// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appinfo} from '../models';

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function ExportDatabase(arg1:string):Promise<void>;

export function GetAppInfo():Promise<appinfo.Info>;

export function GetDataDir():Promise<string>;

export function GetLaunchArgs():Promise<Array<string>>;

export function GetTheme():Promise<string>;

export function OpenDataDir():Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
