// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function GetTheme():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
